### ISSUE TITLE
Faulty timezone communication

### ISSUE THREAD

**Issue by fuesika** [trac-hacks/tracbuildbot#1]
First of all, thanks for this awesome plugin with JSON interface! I deployed it yesterday on our development system and overall it works like a charm.

However, there seem to be some issues with the timezones used and expected by the system, trac, and buildbot.
Running a build at 21:00:00 UTC yields the following information:
- JSON output by buildbot, e.g. json/builders/%s/builds/%d?as_text=1: 22:00:00 (+1, local tz)
- trac/buildbot page: 13:00:00 (???)
- trac/timeline: 21:00:00 (UTC)
- buildbot's waterfall-view displays correctly (it is aware of the corret tz) 22:00:00 (local tz)

I have not yet fully understood the data flow, however from what I understand the class `BuildbotConnector`, method `_parse_build` in `buildbot_api.py` expects local tz and converts to UTC:

``` python
build = dict({
    'builder': data['builderName'],
    'status': status,
    'start' : datetime.utcfromtimestamp(int(data['times'][0])),
    'num': data['number'],
})

if len(data['times']) > 1 and type(data['times'][1]) == float:
    build['finish'] = datetime.utcfromtimestamp(int(data['times'][1]))
```

The JSON handler just passes through, whatever comes is:

``` python
def date_handler(obj):
    return obj.isoformat() if hasattr(obj, 'isoformat') else obj
```

May this be causing this problem?

Finally, the `BuildbotTimeline`'s `get_timeline_events()` in `timeline.py` seems to function correctly. Changing to a UTC-based tz handling would yield the wrong time difference (-1 instead of +1):

``` python
timestamp = datetime.fromtimestamp(build['finish']).replace(tzinfo=localtz)
```

**Comment by Tramort** [comment]
Thank you for your feedback.
I'll try to fix this soon.

**Comment by fuesika** [comment]
Thank you!
